spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.18.201:3306/activiti?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: ourdream528